Completed the tasks
js-tasks-ru/js-20230223_aleksandr-velmozhko pull request #2
Opened 2023-02-28 18:41 UTC by okonoshi

-sort strings
-pick
-omit

2023-02-28 18:42 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-01 09:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === "asc" ? result : result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-03-01 09:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (const key of fields) {
проверьте что вернет вот такой вызов:
```js
pick({}, 'constructor')
```
Почему?

2023-03-01 09:18 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).forEach(([key, value]) => {
👍 good

2023-03-01 09:18 UTC, dosandk requested changes
решения `sortStrings` и `pick` следует поправить

2023-03-01 15:46 UTC, okonoshi commented on 02-javascript-data-types/2-pick/index.js
> +  for (const key of fields) {
Да, забыл что оператор in смотрит и в прототипе.
Можно заменить на Object.hasOwnProperty.call(obj, key) , или лучше все переписать на Object.entries?

2023-03-01 15:47 UTC, okonoshi commented on 02-javascript-data-types/2-pick/index.js
> +  for (const key of fields) {
Да, забыл что оператор in смотрит и в прототипе.
Можно заменить на Object.hasOwnProperty.call(obj, key) , или лучше все переписать на Object.entries?

2023-03-01 16:05 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-01 16:08 UTC, okonoshi commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === "asc" ? result : result.reverse();
Исправил

2023-03-02 12:03 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    result.sort((a, b) => {
подумайте как устранить дубликаты кода

2023-03-02 12:03 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (const key of fields) {
лучше использовать `Object.entries`

2023-03-02 12:04 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (Object.hasOwnProperty.call(obj, key)) {
`call` здесь не нужно использовать

2023-03-02 12:04 UTC, dosandk approved these changes
👍 good

2023-03-02 12:04 UTC, merged